### ISSUE TITLE
iconSrc gets ignored

### ISSUE THREAD

**Issue by JaySunSyn** [expandjs/mat-menu-button#1]
```
 <mat-menu-button target="demoCascading" iconSrc='bower_components/material-design-icons/file/2x_web/ic_folder_open_white_48dp.png'></mat-menu-button>
```

The custom icon source doesn't show. Thanks for your elements!

**Comment by Pupix** [comment]
It doesn't work because **`iconSrc`** is not a supported attribute. What you are looking for is called **`icon-src`**, as the [documentation](http://expandjs.com/elements/mat-menu-button) specifies.
However if on a button there's both, **`icon`** and **`icon-src`**, the former prevails.

`mat-menu-button` was created to be used as is, using the default Material Design menu icon. If you must use a different icon for your menu, either set `icon` to a **falsy** value or just use [mat-icon-button](https://github.com/expandjs/mat-icon-button) and set your own icons that way.
